[paths]
csv_path = "./mock_data.csv"
build_directory = "./mock_data_output/"

[variables]
intensity = "TMSInt"
features = ["participant", "participant_condition"]
response = ['PKPK_APB', 'PKPK_ADM', 'PKPK_ECR', 'PKPK_FCR']

[mcmc]
num_chains = 4
num_warmup = 1000
num_samples = 1000
thinning = 1

[nuts]
target_accept_prob = 0.8
max_tree_depth = 10

# Optional
[mep_metadata]
# This is path to MEP matrix in .npy format, having shape:
# (no. of rows in csv) x (no. of time points) x (no. of responses in MEP matrix)
mep_matrix_path = ""
# Order of muscles in MEP matrix (in its last dimension)
mep_response = ['PKPK_ADM', 'PKPK_APB', 'PKPK_Biceps', 'PKPK_ECR', 'PKPK_FCR', 'PKPK_Triceps']
# Note that, the responses in [mep_metadata].mep_response can be a superset of the responses in [variables].response,
# but only the muscles in [variables].response will be displayed by plotting functions
mep_window = [-0.25, 0.25]
mep_size_window = [0.0065, 0.09]

