[paths]
csv = "/home/vishu/data/mock/mock.csv"
build_dir = "/home/vishu/repos/reports/test_run_01"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_1", "auc_3"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "rectified_logistic"

[optional-mep-data]
mep_matrix_path = "/home/vishu/data/mock/mep_matrix.npy"    # In .npy format with shape: (No. of rows in csv) x (time) x (No. of responses)
mep_time_range = [-0.01, 0.025]

[optional-mep-size-window]
mep_size_time_range = [0.0015, 0.01]

[rectified_logistic]
"µ_a" = [150, 20]
"σ_a" = 20
"σ_b" = 0.5
"σ_L" = 0.05
"σ_H" = 5
"σ_v" = 5
"p" = 10
"g_1" = 20
"g_2" = 20

[saturated_relu]
"µ_a" = [150, 50]
"σ_a" = 50
"σ_b" = 0.1
"σ_L" = 0.05
"σ_H" = 5
"σ_v" = 10

[relu]
"µ_a" = [150, 50]
"σ_a" = 50
"σ_b" = 0.1
"σ_L" = 0.05
"σ_H" = 5
"σ_v" = 10
"g_1" = 20
"g_2" = 20

[aesthetics]
base = 20
