[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hbmep"
version = "0.0.1"
authors = [
    { name="vishu-tyagi", email="vishweshwartyagiv@gmail.com" },
    { name="jrmxn", email="j.mcintoshr@gmail.com"}
]
description = "Package for hierarchical Bayesian modeling of motor evoked potential size"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy==1.24.2",
    "pandas==2.0.2",
    "fastparquet==2023.2.0",
    "scikit-learn==1.2.1",
    "jax[cpu]==0.4.11",
    "flax==0.6.11",
    "numpyro[cpu]==0.12.1",
    "h5py==3.8.0",
    "mat73==0.60",
    "arviz==0.15.1",
    "graphviz==0.20.1",
    "matplotlib==3.7.0",
    "seaborn==0.12.2",
    "jupyter==1.0.0"
]

[project.urls]
"Homepage" = "https://github.com/hbmep/hbmep"
"Bug Tracker" = "https://github.com/hbmep/hbmep/issues"