[paths]
csv_path = "./mock_data.csv"
build_directory = "./mock_data_output/"

[variables]
intensity = "TMSIntensity"
features = ["participant"]
response = ['PKPK_ECR', 'PKPK_FCR']

[mcmc]
num_chains = 4
num_warmup = 1000
num_samples = 1000
thinning = 1

[misc]
base = 10
