PATHS = "paths"
CSV_PATH = "csv_path"
BUILD_DIR = "build_directory"

VARIABLES = "variables"
INTENSITY = "intensity"
FEATURES = "features"
RESPONSE = "response"

MCMC = "mcmc"
CHAINS = "chains"
WARMUP = "warmup"
SAMPLES = "samples"

MEP_DATA = "optional-mep-data"
MEP_MATRIX_PATH = "mep_matrix_path"
MEP_RESPONSE = "mep_response"
MEP_TIME_RANGE = "mep_time_range"
MEP_SIZE_TIME_RANGE = "mep_size_time_range"

MISC = "misc"
BASE = "base"

DATASET_PLOT = "dataset.pdf"
RECRUITMENT_CURVES = "recruitment_curves.pdf"
PRIOR_PREDICTIVE = "prior_predictive_check.pdf"
POSTERIOR_PREDICTIVE = "posterior_predictive_check.pdf"
MCMC_NC = "mcmc.nc"
DIAGNOSTICS_CSV = "diagnostics.csv"
LOO_CSV = "loo.csv"
WAIC_CSV = "waic.csv"

BASE_MODEL = "base_model"
GAMMA_MODEL = "gamma_model"
BOUNDED_OPTIMIZATION = "bound_constrained_optimization"
RELU = "relu"
SATURATED_RELU = "saturated_relu"
RECTIFIED_LOGISTIC = "rectified_logistic"
SEP = "___"
