PATHS = "paths"
CSV_PATH = "csv"
BUILD_DIR = "build_dir"

VARIABLES = "vars"
SUBJECT = "subject"
FEATURES = "features"
INTENSITY = "intensity"
RESPONSE = "response"

MCMC = "mcmc"
CHAINS = "chains"
WARMUP = "warmup"
SAMPLES = "samples"
NUM_CHAINS = "num_chains"
NUM_WARMUP = "num_warmup"
NUM_SAMPLES = "num_samples"

AESTHETICS = "aesthetics"
BASE = "base"

MODEL = "model"
LINK = "link"

OPTIONAL = "optional"
MEP_DATA = "mep_data"
MEP_MATRIX_PATH = "mep_matrix_path"
MEP_TIME_RANGE = "mep_time_range"
MEP_SIZE_WINDOW = "mep_size_window"
MEP_SIZE_TIME_RANGE = "mep_size_time_range"

RAW = "raw_"
DATASET_PLOT = "dataset.pdf"
RECRUITMENT_CURVES = "recruitment_curves.pdf"
PRIOR_PREDICTIVE = "prior_predictive_check.pdf"
POSTERIOR_PREDICTIVE = "posterior_predictive_check.pdf"

BASELINE = "baseline"
RELU = "relu"
SATURATED_RELU = "saturated_relu"
RECTIFIED_LOGISTIC = "rectified_logistic"
