class Site:
    # Model
    a = "a"
    b = "b"
    lo = "lo"
    hi = "hi"
    g = "g"
    noise_offset = "noise_offset"
    noise_slope = "noise_slope"
    p = "p"
    q = "q"

    # Priors
    a_mean = "a_mean"
    a_scale = "a_scale"
    b_mean = "b_mean"
    b_scale = "b_scale"
    lo_scale = "lo_scale"
    hi_scale = "hi_scale"
    g_shape = "g_shape"
    g_scale = "g_scale"
    noise_offset_scale = "noise_offset_scale"
    noise_slope_scale = "noise_slope_scale"

    a_mean_global_scale = "a_mean_global_scale"
    a_scale_global_scale = "a_scale_global_scale"
    b_mean_global_scale = "b_mean_global_scale"
    b_scale_global_scale = "b_scale_global_scale"
    lo_scale_global_scale = "lo_scale_global_scale"
    hi_scale_global_scale = "hi_scale_global_scale"
    g_shape_global_scale = "g_shape_global_scale"
    g_scale_global_scale = "g_scale_global_scale"
    noise_offset_scale_global_scale = "noise_offset_scale_global_scale"
    noise_slope_scale_global_scale = "noise_slope_scale_global_scale"
    Rho = "Rho"

    # Mixed Effects
    baseline_mean_global_scale = "baseline_mean_global_scale"
    baseline_scale_global_scale = "baseline_scale_global_scale"
    delta_mean = "delta_mean"
    delta_scale = "delta_scale"
    baseline_mean = "baseline_mean"
    baseline_scale = "baseline_scale"
    baseline = "baseline"
    delta = "delta"
    penalty = "penalty"
